# Generated by Django 5.2 on 2025-04-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='altura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='imagen_url',
            field=models.URLField(default='https://example.com/default-image.png'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
