# Generated by Django 5.2 on 2025-04-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_altura_pokemon_imagen_url_pokemon_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='numero_pokedex',
            field=models.IntegerField(default=0),
        ),
    ]
